name: Vedant-base

services:
    db:
      image: postgres:16
      container_name: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      ports:
        - "5436:5432"

    redis:
      image: redis:7-alpine
      container_name: redis
      ports:
        - "6379:6379"
        


#docker run -it -name postgres